### PR TITLE
Styling work & Navigation & Cary

### PR DESCRIPTION
**Pull request by jonathonwpowell**
- Improved scaling on desktop / mobile
- Added ability to click outside of the info/legend modal to close
- Added navigation
- Added Cary Greenways & Cary Bike Facilities
- Fixed the location dot bug (happy accident)
- Made Greenways that have a Natural or Gravel material dashed
- Made Greenways in Raleigh that are closed Red & have X symbol through them
- Added custom GIS data for greenway detours
- Added a quick flavicon, feel free to change or reject.  I always just like having one
image

Check it out at: https://adoring-wing-48a930.netlify.com/

### CODE REVIEW

**Comment by pboyer** [comment]
Super cool!

**Comment by jonathonwpowell** [comment]
Thanks! It looks like your website didn't update for some reason

**Comment by pboyer** [comment]
Done! Sorry, I got pulled away by my Dad to go Christmas shopping. 🎄

**Comment by jonathonwpowell** [comment]
No problem, i just thought it was automatically deployed on merge and something had gone wrong. Have a great Christmas!

**Pull request merged**
